
Program     = { Statement };

(* Statements *)
Statement   = { NewLine },
              LetStmt | ExprStmt | EmptyStmt;

LetStmt     = "let", Identifier, "=", Expression, Terminator;
ExprStmt    = Expression, Terminator;
EmptyStmt   = ";";

Terminator  = ";" | Newline;

(* Expressions *)
Expression = PrattExpr;

(* Expression forms *)
nud = Number
    | Identifier
    | "(", Expression, ")"
    | "{", { Statement }, "}" (* TODO *)
    ;

led = "+", Expression
    | "-", Expression
    | "*", Expression
    | "/", Expression
    ;